### ISSUE TITLE
TypeError: can only concatenate str(not "NoneType") to str

### ISSUE THREAD

**Issue by Andrea-Monserrat** [Wilfridovich17/germinando#9]
El error se efectuó en  Nuevo León mercado de abasto estrella de San Nicolás de los Garza, concretamente en la fecha 2013-02-21. 

  File "C:/Users/Andrea Monserrat/Documents/Agrologística/bot_alpha1.py", line 61, in save_day
    linea += ";"+hortaliza[i]

TypeError: can only concatenate str (not "NoneType") to str

**Comment by ghost** [comment]
Revisar versión alpha2. Si el nuevo código funciona, ya cierro el hilo.

**Comment by Andrea-Monserrat** [comment]
alpha2 es el último que subió hace 12 hrs?

**Comment by Andrea-Monserrat** [comment]
La solución fue manejar los dos bots, la version alpha2 solo me arrojo una fecha 21/02/13  (por que hice el ajuste de fechas a 18/02/19 al 01/01/18 pero no me arrojo información) y se complemento con los datos del bot alpha1.
